"""initial schema

Revision ID: a9eb23d92c20
Revises:
Create Date: 2026-05-15 22:35:41.012014

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9eb23d92c20"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "analytics_dashboard_summary_cache",
        "total_payroll",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_dashboard_summary_cache",
        "total_claims",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_dashboard_summary_cache",
        "created_at",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_index(
        "ix_analytics_summary_cache_snapshot_ym",
        "analytics_dashboard_summary_cache",
        ["snapshot_id", "year", "month"],
        unique=True,
    )
    op.alter_column(
        "analytics_monthly_claim_type_spend",
        "amount",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.create_index(
        "ix_analytics_claimtype_month", "analytics_monthly_claim_type_spend", ["snapshot_id", "month"], unique=False
    )
    op.alter_column(
        "analytics_monthly_department_spend",
        "payroll_total",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_monthly_department_spend",
        "claims_total",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_monthly_department_spend",
        "total",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.create_index(
        "ix_analytics_dept_spend_snapshot_dept_month",
        "analytics_monthly_department_spend",
        ["snapshot_id", "department_id", "month"],
        unique=True,
    )
    op.create_index(
        "ix_analytics_dept_spend_snapshot_month",
        "analytics_monthly_department_spend",
        ["snapshot_id", "month"],
        unique=False,
    )
    op.alter_column(
        "analytics_monthly_employee_spend",
        "payroll_total",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_monthly_employee_spend",
        "claims_total",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_monthly_employee_spend",
        "total",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.create_index(
        "ix_analytics_emp_spend_snapshot_emp_month",
        "analytics_monthly_employee_spend",
        ["snapshot_id", "employee_id", "month"],
        unique=False,
    )
    op.create_index(
        "ix_analytics_emp_spend_snapshot_month",
        "analytics_monthly_employee_spend",
        ["snapshot_id", "month"],
        unique=False,
    )
    op.alter_column(
        "data_snapshots",
        "created_at",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.create_index(
        "ix_departments_snapshot_src", "departments", ["snapshot_id", "source_department_key"], unique=False
    )
    op.alter_column(
        "detected_anomalies",
        "baseline_value",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_anomalies",
        "observed_value",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_anomalies",
        "delta_value",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_anomalies",
        "delta_percent",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=8, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.create_index(
        "ix_detected_anomalies_snapshot_month", "detected_anomalies", ["snapshot_id", "month_key"], unique=False
    )
    op.create_index(
        "ix_detected_anomalies_snapshot_type_month",
        "detected_anomalies",
        ["snapshot_id", "anomaly_type", "month_key"],
        unique=False,
    )
    op.create_index("ix_employees_snapshot_dept", "employees", ["snapshot_id", "department_id"], unique=False)
    op.create_index("ix_employees_snapshot_src", "employees", ["snapshot_id", "source_employee_key"], unique=False)
    op.alter_column(
        "expense_claims",
        "amount",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "generated_insights",
        "generated_at",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "generated_insights",
        "total_payroll",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.alter_column(
        "generated_insights",
        "total_claims",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.create_index(
        "ix_generated_insights_snapshot_month", "generated_insights", ["snapshot_id", "current_month"], unique=True
    )
    op.alter_column(
        "payroll_expenses",
        "amount",
        existing_type=sa.FLOAT(),
        type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    op.create_index("ix_refresh_jobs_status", "refresh_jobs", ["status"], unique=False)
    op.create_index("ix_refresh_jobs_status_snapshot", "refresh_jobs", ["status", "snapshot_id"], unique=False)
    op.create_index(
        "ix_source_snapshots_batch_entity", "source_snapshots", ["snapshot_id", "entity_type"], unique=False
    )
    op.create_index(
        "ix_unresolved_mapping_snapshot_entity",
        "unresolved_mapping_issues",
        ["snapshot_id", "entity_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_unresolved_mapping_snapshot_entity", table_name="unresolved_mapping_issues")
    op.drop_index("ix_source_snapshots_batch_entity", table_name="source_snapshots")
    op.drop_index("ix_refresh_jobs_status_snapshot", table_name="refresh_jobs")
    op.drop_index("ix_refresh_jobs_status", table_name="refresh_jobs")
    op.alter_column(
        "payroll_expenses",
        "amount",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.drop_index("ix_generated_insights_snapshot_month", table_name="generated_insights")
    op.alter_column(
        "generated_insights",
        "total_claims",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "generated_insights",
        "total_payroll",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "generated_insights",
        "generated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "expense_claims",
        "amount",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.drop_index("ix_employees_snapshot_src", table_name="employees")
    op.drop_index("ix_employees_snapshot_dept", table_name="employees")
    op.drop_index("ix_detected_anomalies_snapshot_type_month", table_name="detected_anomalies")
    op.drop_index("ix_detected_anomalies_snapshot_month", table_name="detected_anomalies")
    op.alter_column(
        "detected_anomalies",
        "delta_percent",
        existing_type=sa.Numeric(precision=8, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_anomalies",
        "delta_value",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_anomalies",
        "observed_value",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "detected_anomalies",
        "baseline_value",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.drop_index("ix_departments_snapshot_src", table_name="departments")
    op.alter_column(
        "data_snapshots",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.drop_index("ix_analytics_emp_spend_snapshot_month", table_name="analytics_monthly_employee_spend")
    op.drop_index("ix_analytics_emp_spend_snapshot_emp_month", table_name="analytics_monthly_employee_spend")
    op.alter_column(
        "analytics_monthly_employee_spend",
        "total",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_monthly_employee_spend",
        "claims_total",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_monthly_employee_spend",
        "payroll_total",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.drop_index("ix_analytics_dept_spend_snapshot_month", table_name="analytics_monthly_department_spend")
    op.drop_index("ix_analytics_dept_spend_snapshot_dept_month", table_name="analytics_monthly_department_spend")
    op.alter_column(
        "analytics_monthly_department_spend",
        "total",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_monthly_department_spend",
        "claims_total",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_monthly_department_spend",
        "payroll_total",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.drop_index("ix_analytics_claimtype_month", table_name="analytics_monthly_claim_type_spend")
    op.alter_column(
        "analytics_monthly_claim_type_spend",
        "amount",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.drop_index("ix_analytics_summary_cache_snapshot_ym", table_name="analytics_dashboard_summary_cache")
    op.alter_column(
        "analytics_dashboard_summary_cache",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_dashboard_summary_cache",
        "total_claims",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "analytics_dashboard_summary_cache",
        "total_payroll",
        existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
