"""add pipeline_run_telemetry and daily_pipeline_rollups

Revision ID: b7d4e1f3a8c2
Revises: a1b2c3d4e5f6
Create Date: 2026-05-29 10:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7d4e1f3a8c2"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_run_telemetry",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("tenant_id", sa.String(36), nullable=False),
        sa.Column("pipeline_id", sa.String(255), nullable=False),
        sa.Column("job_type", sa.String(100), nullable=False),
        sa.Column("run_id", sa.String(36), nullable=False),
        sa.Column("dataset_id", sa.String(36), nullable=True),
        sa.Column("connection_id", sa.String(36), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="success"),
        sa.Column("duration_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("bytes_written", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("rows_processed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_message", sa.Text(), nullable=False, server_default=""),
        sa.Column("warning_message", sa.Text(), nullable=False, server_default=""),
        sa.Column("latency_threshold_ms", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("(now() at time zone 'utc')"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pipeline_run_telemetry_tenant_id",
        "pipeline_run_telemetry",
        ["tenant_id"],
    )
    op.create_index(
        "ix_pipeline_run_telemetry_pipeline_id",
        "pipeline_run_telemetry",
        ["pipeline_id"],
    )
    op.create_index(
        "ix_pipeline_run_telemetry_run_id",
        "pipeline_run_telemetry",
        ["run_id"],
    )

    op.create_table(
        "daily_pipeline_rollups",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("tenant_id", sa.String(36), nullable=False),
        sa.Column("pipeline_id", sa.String(255), nullable=False),
        sa.Column("job_type", sa.String(100), nullable=False),
        sa.Column("date", sa.String(10), nullable=False),
        sa.Column("run_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("success_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("failed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("warning_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("total_duration_ms", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("total_bytes_written", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("total_rows_processed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("max_duration_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("sla_violation_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("(now() at time zone 'utc')"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_daily_pipeline_rollups_tenant_id",
        "daily_pipeline_rollups",
        ["tenant_id"],
    )
    op.create_index(
        "ix_daily_pipeline_rollups_pipeline_id",
        "daily_pipeline_rollups",
        ["pipeline_id"],
    )
    op.create_index(
        "ix_daily_pipeline_rollups_date",
        "daily_pipeline_rollups",
        ["date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("daily_pipeline_rollups")
    op.drop_table("pipeline_run_telemetry")
